### ISSUE TITLE
Compatibility with recent protobuf

### ISSUE THREAD

**Issue by rollick** [getamis/grpc-contract#14] opened 2018-05-23 12:34 UTC
Thanks for opening this repo! I was playing around with a simple solidity contract which partly worked but I was unable to generate the grpc server code. The latest protobuf is now adding additional fields to response types. Here is some info: https://groups.google.com/forum/#!topic/protobuf/N-elvFu4dFM and an example of my response struct in messages.pb.go:
```
type SayResp struct {
	Arg                  string   `protobuf:"bytes,1,opt,name=arg" json:"arg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}
```
I am happy to continue tinkering until I fix this but I was wondering if there is any code incoming to fix grpc-contract on more recent versions of protobuf. Cheers!

**Comment by bailantaotao** [comment] 2018-05-31 11:15
Thanks for your friendly reminder.

We already have a PR to fix this.
https://github.com/getamis/grpc-contract/pull/15

**Comment by bailantaotao** [comment] 2018-06-01 08:52
The PR has been merged.

Please use the latest version to build.

If the taint issue is still happening, please reopen the issue and change the title, it might be caused by something else.

**Closed as completed by bailantaotao** 2018-06-01 08:52 UTC
